#pragma once

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5

#define TOTAL_ROWS 4
#define TOTAL_COLUMNS TOTAL_ROWS
#define TOTAL_PARTS  TOTAL_ROWS*TOTAL_COLUMNS-1

#define BOARD_SCALE_SIZE 0.8